export {default as Footer} from './Footer/Footer'
export * from './benefit'
export {default as ContactUs} from './contactUs/ContactUs'
export * from './contactUs/FormContactUs'
export {default as DemoRequest} from './demoRequest/DemoRequest'
export {default as HowItWorks} from './howItWorks/HowItWorks'
export {default as NavBar} from './navbar/NavBar'
export {default as CardScenarios} from './scenarios/CardScenarios'
export {default as Scenarios} from './scenarios/Scenarios'
export {default as WhatIs} from './whatIs/WhatIs'
